
version: '3.4'

services:
  chatroomservercli:
    network_mode: "host"
    ports:
      - "25565:25565"
    image: chatroomservercli
    build:
      context: .
      dockerfile: ChatroomServerCLI/Dockerfile
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
